##springboot整合rabbitmq基本配置


spring:
  rabbitmq:
    addresses: 193.112.214.43
    username: guest
    password: guest
    connection-timeout: 15000
    virtual-host: /
    publisher-confirms: true #消息确认模式
    publisher-returns: true #
    template:
      mandatory: true
  http:
    encoding:
      charset: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


server:
  servlet:
    context-path: /
  port: 8001


